spring:
  application:
    name: showmantra-backend
  datasource:
    url: jdbc:mysql://localhost:3306/showmantra_db?createDatabaseIfNotExist=true
    username: root
    password: ranjan@1
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
